# docker-compose.prod.yml
version: '3'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    ports:
      - "8080:8080"
    environment:
      NODE_ENV: production
      DB_USER: cineinfo
      DATABASE_HOST: postgresql-cineinfo.alwaysdata.net
      DATABASE_NAME: cineinfo_projet
      DB_PASSWORD: cineinfo123/
      DATABASE_PORT: 5432
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    ports:
      - "3000:3000"
  database:
    image: postgres:latest
    environment:
      POSTGRES_DB: cineinfo_projet
      POSTGRES_USER: cineinfo
      POSTGRES_PASSWORD: cineinfo123/
  reverseproxy:
    restart: always
    build:
      context: reverse-proxy/
      dockerfile: ./Dockerfile.prod
    depends_on:
      - backend
      - frontend
    volumes:
      - ./reverse-proxy/log:/var/log/nginx
    ports:
      - 8090:80
