# docker-compose.prod.yml
version: '3'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    ports:
      - "8080:8080"
    environment:
      NODE_ENV: production
      DB_USER: postgres
      DATABASE_HOST: database
      DATABASE_NAME: postgres
      DB_PASSWORD: postgre
      DATABASE_PORT: 5432
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    ports:
      - "3000:3000"
  database:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgre
    volumes:
      - ./database:/docker-entrypoint-initdb.d
  reverseproxy:
    restart: always
    build:
      context: reverse-proxy/
      dockerfile: ./Dockerfile.prod
    depends_on:
      - backend
      - frontend
    volumes:
      - ./reverse-proxy/log:/var/log/nginx
    ports:
      - 8090:80
  redis:
    image: redis:latest
    volumes:
      - redis-data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]

volumes:
  redis-data:
