FROM node:21 as builder
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN mkdir -p ./dist && npm run build

FROM node:21
WORKDIR /app
COPY package*.json ./
RUN npm ci --only=production
COPY --from=builder /app/dist ./dist

EXPOSE 80
CMD ["node", "dist/app.bundle.min.cjs"]
